"""Observability, Telemetry, Distributed Tracing & Persistence Package for PayPilot."""

from backend.observability.audit import (
    AuditEvent,
    BaseAuditStore,
    InMemoryAuditStore,
    SQLAuditStore,
    get_audit_store,
    record_audit_event,
    reset_audit_store,
    set_audit_store,
)
from backend.observability.metrics import (
    get_metrics_snapshot,
    metrics_registry,
    record_agent_execution,
    record_error,
    record_llm_call,
    record_request,
    record_retry,
    reset_metrics,
)
from backend.observability.slo import (
    SLOBreachEvent,
    calculate_slo_metrics,
    evaluate_slo_breaches,
)
from backend.observability.store import (
    BaseMetricsStore,
    InMemoryMetricsStore,
    RedisMetricsStore,
    get_metrics_store,
    set_metrics_store,
)
from backend.observability.tracing import (
    BaseTraceStore,
    InMemoryTraceStore,
    SpanRecord,
    TraceContext,
    get_current_trace_context,
    get_trace_store,
    reset_trace_context,
    reset_trace_store,
    set_current_trace_context,
    set_trace_store,
    trace_span,
)

__all__ = [
    "metrics_registry",
    "record_request",
    "record_agent_execution",
    "record_llm_call",
    "record_retry",
    "record_error",
    "get_metrics_snapshot",
    "reset_metrics",
    "BaseMetricsStore",
    "InMemoryMetricsStore",
    "RedisMetricsStore",
    "get_metrics_store",
    "set_metrics_store",
    "AuditEvent",
    "BaseAuditStore",
    "InMemoryAuditStore",
    "SQLAuditStore",
    "get_audit_store",
    "set_audit_store",
    "record_audit_event",
    "reset_audit_store",
    "TraceContext",
    "SpanRecord",
    "BaseTraceStore",
    "InMemoryTraceStore",
    "get_trace_store",
    "set_trace_store",
    "reset_trace_store",
    "trace_span",
    "get_current_trace_context",
    "set_current_trace_context",
    "reset_trace_context",
    "SLOBreachEvent",
    "calculate_slo_metrics",
    "evaluate_slo_breaches",
]
