import {
  AnalyzeResponse,
  AuditEventSchema,
  ConfigDiagnosticsSchema,
  JobResponse,
  SLOResponseSchema,
  TransactionRecord,
} from '../types/api';

export const MOCK_TRANSACTIONS: TransactionRecord[] = [
  {
    transaction_id: 'txn_984729103841',
    timestamp: '2026-08-25 10:45:12',
    merchant_id: 'merchant_enterprise_01',
    customer_id: 'cust_849201',
    amount: 14500.0,
    payment_method: 'UPI',
    payment_status: 'SUCCESS',
    failure_reason: 'None',
    device_type: 'Mobile',
    customer_type: 'Returning',
    product_category: 'Electronics',
    refund_status: 'NO_REFUND',
    checkout_step_reached: 'PAYMENT_COMPLETED',
  },
  {
    transaction_id: 'txn_773820194820',
    timestamp: '2026-08-25 10:42:05',
    merchant_id: 'merchant_enterprise_01',
    customer_id: 'cust_394012',
    amount: 3200.0,
    payment_method: 'UPI',
    payment_status: 'FAILED',
    failure_reason: 'GATEWAY_TIMEOUT',
    device_type: 'Mobile',
    customer_type: 'New',
    product_category: 'Fashion',
    refund_status: 'NO_REFUND',
    checkout_step_reached: 'PAYMENT',
  },
  {
    transaction_id: 'txn_664920184719',
    timestamp: '2026-08-25 10:38:50',
    merchant_id: 'merchant_enterprise_01',
    customer_id: 'cust_910284',
    amount: 28900.0,
    payment_method: 'Credit_Card',
    payment_status: 'SUCCESS',
    failure_reason: 'None',
    device_type: 'Desktop',
    customer_type: 'VIP',
    product_category: 'Electronics',
    refund_status: 'NO_REFUND',
    checkout_step_reached: 'PAYMENT_COMPLETED',
  },
  {
    transaction_id: 'txn_558392018472',
    timestamp: '2026-08-25 10:30:19',
    merchant_id: 'merchant_enterprise_01',
    customer_id: 'cust_294810',
    amount: 1850.0,
    payment_method: 'Wallet',
    payment_status: 'SUCCESS',
    failure_reason: 'None',
    device_type: 'Mobile',
    customer_type: 'Returning',
    product_category: 'Grocery',
    refund_status: 'NO_REFUND',
    checkout_step_reached: 'PAYMENT_COMPLETED',
  },
  {
    transaction_id: 'txn_449201948201',
    timestamp: '2026-08-25 10:22:44',
    merchant_id: 'merchant_enterprise_01',
    customer_id: 'cust_482019',
    amount: 7600.0,
    payment_method: 'Net_Banking',
    payment_status: 'REFUNDED',
    failure_reason: 'None',
    device_type: 'Desktop',
    customer_type: 'Returning',
    product_category: 'Beauty',
    refund_status: 'REFUNDED',
    checkout_step_reached: 'PAYMENT_COMPLETED',
  },
  {
    transaction_id: 'txn_339201847201',
    timestamp: '2026-08-25 10:15:30',
    merchant_id: 'merchant_enterprise_01',
    customer_id: 'cust_102948',
    amount: 9800.0,
    payment_method: 'UPI',
    payment_status: 'FAILED',
    failure_reason: 'ISSUER_UNAVAILABLE',
    device_type: 'Mobile',
    customer_type: 'New',
    product_category: 'Fashion',
    refund_status: 'NO_REFUND',
    checkout_step_reached: 'PAYMENT',
  },
  {
    transaction_id: 'txn_229103847291',
    timestamp: '2026-08-25 10:05:11',
    merchant_id: 'merchant_enterprise_01',
    customer_id: 'cust_582910',
    amount: 45000.0,
    payment_method: 'Credit_Card',
    payment_status: 'SUCCESS',
    failure_reason: 'None',
    device_type: 'Desktop',
    customer_type: 'VIP',
    product_category: 'Home',
    refund_status: 'NO_REFUND',
    checkout_step_reached: 'PAYMENT_COMPLETED',
  },
  {
    transaction_id: 'txn_119284729102',
    timestamp: '2026-08-25 09:58:02',
    merchant_id: 'merchant_enterprise_01',
    customer_id: 'cust_739201',
    amount: 5400.0,
    payment_method: 'Debit_Card',
    payment_status: 'FAILED',
    failure_reason: 'INSUFFICIENT_FUNDS',
    device_type: 'Mobile',
    customer_type: 'Returning',
    product_category: 'Electronics',
    refund_status: 'NO_REFUND',
    checkout_step_reached: 'PAYMENT',
  },
];

export const MOCK_SUMMARY = {
  total_gross_volume_inr: 84250000.0,
  realized_revenue_inr: 72455000.0,
  total_lost_revenue_inr: 11795000.0,
  recoverable_opportunity_inr: 6850000.0,
  overall_success_rate_pct: 86.0,
  average_transaction_value_inr: 5616.67,
  total_transactions_count: 15000,
  successful_transactions_count: 12900,
  failed_transactions_count: 2100,
};

export const MOCK_PAYMENT_METHODS_HEALTH = [
  { method: 'UPI', share_pct: 45.2, success_rate_pct: 79.4, lost_inr: 4820000, status: 'warning' },
  { method: 'Credit_Card', share_pct: 28.6, success_rate_pct: 92.1, lost_inr: 2100000, status: 'healthy' },
  { method: 'Debit_Card', share_pct: 14.1, success_rate_pct: 88.5, lost_inr: 1450000, status: 'healthy' },
  { method: 'Net_Banking', share_pct: 8.3, success_rate_pct: 84.0, lost_inr: 920000, status: 'healthy' },
  { method: 'Wallet', share_pct: 3.8, success_rate_pct: 94.8, lost_inr: 210000, status: 'healthy' },
];

export const MOCK_CHECKOUT_FUNNEL = [
  { step: 'Cart View', count: 24500, drop_pct: 0, conversion_pct: 100 },
  { step: 'Shipping Details', count: 19800, drop_pct: 19.2, conversion_pct: 80.8 },
  { step: 'Payment Selection', count: 17200, drop_pct: 13.1, conversion_pct: 70.2 },
  { step: 'Completed Order', count: 15000, drop_pct: 12.8, conversion_pct: 61.2 },
];

export const MOCK_DEVICE_COMPARISON = {
  mobile: {
    sessions: 16500,
    completed: 9100,
    conversion_rate_pct: 55.15,
    failure_rate_pct: 20.8,
  },
  desktop: {
    sessions: 8000,
    completed: 5900,
    conversion_rate_pct: 73.75,
    failure_rate_pct: 7.9,
  },
  gap_pct: 18.6,
  lost_revenue_mobile_inr: 4950000.0,
};

export const MOCK_AI_ANALYSIS: AnalyzeResponse = {
  query: 'Why did my revenue decrease and where is my biggest drop-off?',
  intent: 'revenue',
  agents_participated: ['revenue_agent', 'payment_agent', 'checkout_agent', 'customer_agent', 'recovery_agent'],
  key_facts: {
    total_gross_volume_inr: 84250000.0,
    realized_revenue_inr: 72455000.0,
    total_lost_revenue_inr: 11795000.0,
    payment_success_rate_pct: 86.0,
    worst_payment_method: 'UPI (79.4% success rate)',
    mobile_desktop_conversion_gap_pct: 18.6,
    highest_refund_category: 'Fashion (14.8% refund rate)',
  },
  revenue_leaks: [
    'UPI Gateway Timeouts: 482 failed transactions causing INR 3,850,000 lost gross volume.',
    'Mobile Checkout Form Friction: Mobile users drop off 18.6% more frequently than desktop users at the shipping step.',
    'Fashion Product Category Refund Spikes: Sizing-related returns contribute to INR 1,820,000 in refunded volume.',
  ],
  prioritized_actions: [
    {
      rank: 1,
      action: 'Implement Dynamic Multi-Gateway Failover Routing for UPI',
      problem: 'Primary UPI gateway experiences recurring 504 gateway timeouts during peak evening trading hours.',
      affected_area: 'Payment Gateway Infrastructure (UPI)',
      estimated_revenue_impact_inr: 3850000.0,
      observed_loss_inr: 4820000.0,
      confidence: 0.94,
      effort: 'Low',
      urgency: 'High',
      priority_score: 96.5,
      reasoning: 'Rerouting failed UPI attempts automatically to secondary bank rails recaptures ~80% of lost transactions with zero frontend disruption.',
    },
    {
      rank: 2,
      action: 'Streamline Mobile 1-Click Checkout & Autofill Form Fields',
      problem: 'Mobile users abandon the checkout funnel at step 2 (Shipping) due to redundant address fields.',
      affected_area: 'Mobile Web & App Checkout Funnel',
      estimated_revenue_impact_inr: 2100000.0,
      observed_loss_inr: 3200000.0,
      confidence: 0.89,
      effort: 'Medium',
      urgency: 'High',
      priority_score: 88.2,
      reasoning: 'Enabling browser autofill and Google Pay / Apple Pay express sheets directly on the product page bridges the 18.6% mobile conversion gap.',
    },
    {
      rank: 3,
      action: 'Introduce Interactive Size Recommendation Widget in Fashion',
      problem: 'Fashion apparel items show an elevated 14.8% refund rate primarily flagged for sizing mismatches.',
      affected_area: 'Catalog Experience & Post-Purchase',
      estimated_revenue_impact_inr: 900000.0,
      observed_loss_inr: 1820000.0,
      confidence: 0.82,
      effort: 'Low',
      urgency: 'Medium',
      priority_score: 79.0,
      reasoning: 'Providing customer measurements and fit advisor cards decreases size-induced returns by an estimated 50%.',
    },
  ],
  executive_recommendation:
    'Execute P1 (Implement Dynamic Multi-Gateway Failover Routing for UPI) immediately to recover an estimated INR 3,850,000. Follow with P2 (Streamline Mobile 1-Click Checkout) to unlock an additional INR 2,100,000.',
  final_answer:
    '### Executive Diagnostic Summary\n\nPayPilot multi-agent analysis identified a total recoverable revenue pool of **INR 6,850,000**. The primary driver of lost revenue is concentrated in **UPI payment failures** (INR 4.82M loss) followed by **mobile checkout abandonment** (INR 3.2M loss).\n\nImmediate deployment of smart multi-rail routing will restore payment completion rates above 94% within 48 hours.',
  estimated_recovery: {
    total_recoverable_inr: 6850000.0,
    quick_wins_inr: 4750000.0,
    strategic_inr: 2100000.0,
  },
  llm_provider: 'nvidia',
  model: 'meta/llama-3.3-70b-instruct',
  is_live_llm: false,
  execution_metadata: {
    request_id: 'req_849201849102',
    trace_id: 'tr_4892019482019482',
    query: 'Why did my revenue decrease and where is my biggest drop-off?',
    detected_intent: 'revenue',
    executed_agents: ['revenue_agent', 'payment_agent', 'checkout_agent', 'customer_agent', 'recovery_agent'],
    execution_duration_ms: 142.5,
    llm_provider: 'nvidia',
    model: 'meta/llama-3.3-70b-instruct',
    is_live_llm: false,
    success: true,
    timestamp: '2026-08-25T05:00:00Z',
  },
};

export const MOCK_JOBS: JobResponse[] = [
  {
    job_id: 'job_285c2d0fc0e3',
    task_type: 'async_analysis',
    client_id: 'merchant_enterprise_01',
    role: 'analyst',
    status: 'completed',
    created_at: '2026-08-25T05:10:00Z',
    started_at: '2026-08-25T05:10:01Z',
    completed_at: '2026-08-25T05:10:03Z',
    duration_ms: 2150.4,
    query_summary: 'Perform a complete audit of my revenue leakage across all...',
    result: MOCK_AI_ANALYSIS,
  },
  {
    job_id: 'job_41b74b813aa0',
    task_type: 'async_analysis',
    client_id: 'merchant_enterprise_01',
    role: 'analyst',
    status: 'completed',
    created_at: '2026-08-25T04:45:00Z',
    started_at: '2026-08-25T04:45:01Z',
    completed_at: '2026-08-25T04:45:02Z',
    duration_ms: 1820.1,
    query_summary: 'Why are UPI transactions failing and what are the top...',
    result: {
      intent: 'payment',
      priority_actions: [MOCK_AI_ANALYSIS.prioritized_actions[0]],
      final_answer: 'UPI Gateway analysis completed successfully.',
    },
  },
  {
    job_id: 'job_99a81b2c4d5e',
    task_type: 'async_analysis',
    client_id: 'merchant_enterprise_01',
    role: 'analyst',
    status: 'running',
    created_at: '2026-08-25T05:30:00Z',
    started_at: '2026-08-25T05:30:01Z',
    duration_ms: null,
    query_summary: 'Simulate the additional revenue unlocked if payment success...',
  },
];

export const MOCK_AUDIT_LOGS: AuditEventSchema[] = [
  {
    event_id: 'evt_849201948201',
    event_type: 'analysis_executed',
    timestamp: '2026-08-25T05:28:10Z',
    request_id: 'req_394820194820',
    endpoint: '/api/v1/analyze',
    http_method: 'POST',
    client_id: 'merchant_enterprise_01',
    role: 'analyst',
    status: 'success',
    status_code: 200,
    duration_ms: 124.5,
    intent: 'revenue',
    executed_agents: ['revenue_agent', 'payment_agent', 'checkout_agent', 'customer_agent', 'recovery_agent'],
    llm_provider: 'nvidia',
    model: 'meta/llama-3.3-70b-instruct',
    fallback_used: false,
    query_summary: 'Why did my revenue decrease and where is my biggest...',
  },
  {
    event_id: 'evt_773920184729',
    event_type: 'job_submitted',
    timestamp: '2026-08-25T05:10:00Z',
    request_id: 'req_284920184729',
    endpoint: '/api/v1/jobs',
    http_method: 'POST',
    client_id: 'merchant_enterprise_01',
    role: 'analyst',
    status: 'success',
    status_code: 202,
    duration_ms: 12.8,
    query_summary: 'Perform a complete audit of my revenue leakage...',
  },
  {
    event_id: 'evt_664829104820',
    event_type: 'readiness_probe',
    timestamp: '2026-08-25T05:00:00Z',
    request_id: 'req_119284729102',
    endpoint: '/ready',
    http_method: 'GET',
    client_id: 'system_kubelet',
    role: 'system',
    status: 'success',
    status_code: 200,
    duration_ms: 2.1,
  },
];

export const MOCK_SLO_STATUS: SLOResponseSchema = {
  overall_status: 'HEALTHY',
  total_slos_evaluated: 4,
  active_breaches_count: 0,
  new_alerts_emitted_count: 0,
  evaluated_slos: [
    {
      slo_name: 'Analyze P95 Latency',
      observed_value: 170.8,
      target_value: 1500.0,
      unit: 'ms',
      status: 'healthy',
      severity: 'low',
      timestamp: '2026-08-25T05:30:00Z',
      details: { sample_count: 32 },
    },
    {
      slo_name: 'API Error Rate',
      observed_value: 0.0,
      target_value: 1.0,
      unit: '%',
      status: 'healthy',
      severity: 'low',
      timestamp: '2026-08-25T05:30:00Z',
      details: { total_requests: 1250 },
    },
    {
      slo_name: 'Job Execution Success Rate',
      observed_value: 100.0,
      target_value: 99.0,
      unit: '%',
      status: 'healthy',
      severity: 'low',
      timestamp: '2026-08-25T05:30:00Z',
      details: { completed_jobs: 25 },
    },
    {
      slo_name: 'Database Pool Utilization',
      observed_value: 36.0,
      target_value: 80.0,
      unit: '%',
      status: 'healthy',
      severity: 'low',
      timestamp: '2026-08-25T05:30:00Z',
      details: { active_conns: 36, max_conns: 100 },
    },
  ],
  active_breaches: [],
  new_alerts_emitted: [],
  metrics_evaluated: {
    p95_latency_ms: 170.8,
    error_rate_pct: 0.0,
    job_success_pct: 100.0,
  },
  timestamp: '2026-08-25T05:30:00Z',
};

export const MOCK_CONFIG_DIAGNOSTICS: ConfigDiagnosticsSchema = {
  status: 'valid',
  environment: 'production',
  llm_provider: 'nvidia',
  model: 'meta/llama-3.3-70b-instruct',
  database_backend: 'postgres',
  job_store: 'sql',
  rate_limit_backend: 'redis',
  tracing: 'enabled',
  secrets_status: {
    DATABASE_URL: 'configured',
    REDIS_URL: 'configured',
    PAYPILOT_API_KEY: 'configured',
    NVIDIA_API_KEY: 'configured',
  },
  snapshot: {
    FASTAPI_HOST: '0.0.0.0',
    FASTAPI_PORT: 8000,
    DB_POOL_SIZE: 5,
    DB_MAX_OVERFLOW: 10,
    JOB_MAX_WORKERS: 3,
    JOB_LEASE_TIMEOUT_SECONDS: 300,
    SHUTDOWN_TIMEOUT_SECONDS: 15.0,
    REQUIRE_AUTH: true,
  },
  timestamp: '2026-08-25T05:30:00Z',
};
