apiVersion: v1
kind: Namespace
metadata:
  name: paypilot
  labels:
    app.kubernetes.io/name: paypilot
    app.kubernetes.io/part-of: paypilot
    app.kubernetes.io/managed-by: kustomize
    environment: production
